### ISSUE TITLE
FFXVBINMOD files from Steam Workshop become corrupted when modified

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#10]
This bug occurs when opening a Steam Workshop mod card in Flagrum and then saving it.

The exact issue is not currently known, but it seems to corrupt the FFXVBINMOD file. One user reported that their game crashes after modifying a mod in this way, but this doesn't appear to be the case for all users. However, if trying to edit that same mod again in future, Flagrum will crash when attempting to save with the following log:

```
System.OverflowException
Message: Arithmetic operation resulted in an overflow.
Stack Trace:    at Flagrum.Core.Archive.Unpacker.ReadFileData(ArchiveFile file) in C:\Code\Flagrum\Flagrum.Core\Archive\Unpacker.cs:line 130
   at Flagrum.Core.Archive.Unpacker.ReadDataForAllFiles() in C:\Code\Flagrum\Flagrum.Core\Archive\Unpacker.cs:line 123
   at Flagrum.Core.Archive.Unpacker.ToPacker() in C:\Code\Flagrum\Flagrum.Core\Archive\Unpacker.cs:line 113
   at Flagrum.Web.Features.ModLibrary.Editor.Index.SaveAsync() in C:\Code\Flagrum\Flagrum.Web\Features\ModLibrary\Editor\Index.razor.cs:line 235
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Flagrum.Desktop.App.Main()
```

This was only tested on weapon mods and Steam Workshop subscriptions. The developer should consider also testing local mods and other mod types like outfits.

**Comment by Kizari** [comment]
This issue appears to only affect binmods that were not made with Flagrum (i.e. they were made with Mod Organizer).

**Comment by Kizari** [comment]
Further to this, it appears that the sizes in the individual file headers are wrong after reserialising the binmod. They appear correct when reading the binmod though, so perhaps something about these particular archives (flags, version, protect hash?) is causing this to be serialised incorrectly. Unfortunately as this turned out to not be a quick fix, this will be delayed for a future update.

**Comment by Kizari** [comment]
This has been fixed in Flagrum 1.3.3.
