### ISSUE TITLE
Flagrum fails to find Current Earc Preview resulting in crash and missing backup

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#16]
While building a new mod that replaced multiple .btex files. User encountered the following error after selecting save. 

`'C:\Users\Rinual\AppData\Local\Flagrum\app-1.2.5\wwwroot\images\current_earc_preview.png'.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Flagrum.Web.Persistence.Entities.EarcMod.UpdateThumbnail() in C:\Code\Flagrum\Flagrum.Web\Persistence\Entities\EarcMod.cs:line 242
   at Flagrum.Web.Persistence.Entities.EarcMod.Save(FlagrumDbContext context, ILogger logger) in C:\Code\Flagrum\Flagrum.Web\Persistence\Entities\EarcMod.cs:line 152
   at Flagrum.Web.Features.EarcMods.Editor.<OnSubmit>b__43_5() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 260
   at Flagrum.Web.Features.EarcMods.Editor.CheckConflicts(Func`1 onYes, Func`1 onNo) in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 325
   at Flagrum.Web.Features.EarcMods.Editor.<OnSubmit>b__43_2() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 257
   at Flagrum.Web.Features.EarcMods.Editor.OnSubmit() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 257
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

After receiving this crash, user noticed a default Flagrum assigned thumbnail missing for the mod. 

When user attempted to re-save that mod, a second crash was reported for a variant reason. 

`  
Could not find file 'C:\Users\Rinual\AppData\Local\Flagrum\earc\backup\2420519083472462009'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Flagrum.Web.Persistence.Entities.EarcMod.Revert(FlagrumDbContext context) in C:\Code\Flagrum\Flagrum.Web\Persistence\Entities\EarcMod.cs:line 415
   at Flagrum.Web.Persistence.Entities.EarcMod.Save(FlagrumDbContext context, ILogger logger) in C:\Code\Flagrum\Flagrum.Web\Persistence\Entities\EarcMod.cs:line 146
   at Flagrum.Web.Features.EarcMods.Editor.<OnSubmit>b__43_5() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 260
   at Flagrum.Web.Features.EarcMods.Editor.CheckConflicts(Func`1 onYes, Func`1 onNo) in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 325
   at Flagrum.Web.Features.EarcMods.Editor.<OnSubmit>b__43_2() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 257
   at Flagrum.Web.Features.EarcMods.Editor.OnSubmit() in C:\Code\Flagrum\Flagrum.Web\Features\EarcMods\Editor.razor:line 257
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState `
[crash.txt](https://github.com/Kizari/Flagrum/files/9542133/crash.txt)

![image](https://user-images.githubusercontent.com/108095289/189519811-24f3d33b-a342-4565-9bcf-ce8962193d4e.png)

![image](https://user-images.githubusercontent.com/108095289/189520409-a871f486-0783-42e0-836f-891a6160e59a.png)

This bug was replicated in a later attempt with a fresh rebuilding of the mod after fixing the above issue. However, it was not the first time recreating the mod, but a further attempt adding to the mod once it appeared to be rectified. 

User was successfully able to save the mod after disabling the mod manually using external methods outside of Flagrum, and resaving the mod without recreating it and without further need for rectifying the missing preview image. 

Note: Only abnormal part of users traditional workflow was having a second instance of Flagrum open while creating the mod. Further testing from user is required to verify if this is related.

**Comment by Kizari** [comment]
These issues have been solved as of Flagrum 1.3.
