### ISSUE TITLE
[Bug]: Flagrum Blender won't import enemy models

### ISSUE THREAD

**Issue by EratoTiaTuatha** [Kizari/Flagrum#166]
### Operating System

Windows 11 64-Bit

### Game Version

Latest Steam Release

### Version

Blender add-on 1.3.3

### Description of the bug

While nh folder imports (that I tested) work okay, anything from the enemy folders throws an error and only imports the armature, no meshes. 
Models that definitely don't work include me00 and me07, imported without LODs.
Tested using both Flagrum exports of the files and older Scout exports, all of which worked previously.

### Steps to reproduce the bug

1. Open Blender 3.0
2. Import=>Flagrum=>gfxbin
3. Select an enemy model, such as me07
4. armature is imported, meshes are not, and an error is thrown

### Crash logs

Python: Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Flagrum\import_export\menu.py", line 71, in execute
    importer.import_meshes()
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Flagrum\import_export\gmdlimporter.py", line 98, in import_meshes
    self.buffer = Interop.import_gpubin(self.context.gfxbin_path, self.context.import_lods,
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Flagrum\import_export\interop.py", line 47, in import_gpubin
    Interop.run_command(command)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Flagrum\import_export\interop.py", line 24, in run_command
    raise RuntimeError("An exception occured during the operation of Flagrum.Blender.exe")
RuntimeError: An exception occured during the operation of Flagrum.Blender.exe

location: <unknown location>:-1

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Rinual** [comment]
![image](https://github.com/user-attachments/assets/15f30050-4517-43d8-bcbf-c279b87d2c21)
dont mind the texture issue, i was using an export that was using .dds

**Comment by Rinual** [comment]
![image](https://github.com/user-attachments/assets/8c6663b1-e02d-4238-8336-0bf8d8944afb)

**Comment by EratoTiaTuatha** [comment]
Confirmed re-exports from Flagrum do work in Blender, but that's only half of what my issue is. Is there a reason my old exports (both Scout and Flagrum) don't work? I wouldn't expect the exporting process to touch the content of a gfxbin file at all. I verified the old exported gfxbins in Noesis and they still work there, so it's not any kind of file/drive corruption. Do I have to re-export the entire game to have it work with the current version of the Flagrum add-on?

**Comment by Rinual** [comment]
hmm, i'm not sure, if you send me the gmdl and gpubin of the ones that don't work, i can try to see what changed in the exports / test if its still broken on mine. The blender addon hasn't been touched in a very long time though. like 1.5 years. but all the old builds of it are still available if that's easier for you, https://github.com/Kizari/Flagrum-Blender/releases
