### ISSUE TITLE
Unhandled exception while exporting nh02_040.gmdl with dependencies

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#23]
**See end of post for workaround**

## The Problem

A user has reported that while exporting nh02_040.gmdl with dependencies, Flagrum would throw an error and fail to export.

![image](https://user-images.githubusercontent.com/25322543/195988737-b10adf9a-7e01-4e8b-b8db-4f109fcf0b47.png)

This error is very reproducible by simply trying to do the same.

Console output as follows:
```
Arithmetic operation resulted in an overflow.
   at Flagrum.Core.Gfxbin.Btex.BtexConverter.BtexToDds(Byte[] btex) in C:\Code\Flagrum\Flagrum.Core\Gfxbin\Btex\BtexConverter.cs:line 46
   at Flagrum.Web.Services.TextureConverter.BtexToScratchImage(Byte[] btex) in C:\Code\Flagrum\Flagrum.Web\Services\TextureConverter.cs:line 267
   at Flagrum.Web.Services.TextureConverter.BtexToPng(Byte[] btex) in C:\Code\Flagrum\Flagrum.Web\Services\TextureConverter.cs:line 231
   at Flagrum.Web.Features.AssetExplorer.Export.ExportWithDependenciesModal.ConvertTexture(Byte[] btex) in C:\Code\Flagrum\Flagrum.Web\Features\AssetExplorer\Export\ExportWithDependenciesModal.razor:line 268
   at Flagrum.Web.Features.AssetExplorer.Export.ExportWithDependenciesModal.<>c__DisplayClass23_0.<Export>b__0(String path) in C:\Code\Flagrum\Flagrum.Web\Features\AssetExplorer\Export\ExportWithDependenciesModal.razor:line 122
   at Flagrum.Desktop.Services.WpfService.OpenSaveFileDialogAsync(String defaultName, String filter, Action`1 onFileSelected) in C:\Code\Flagrum\Flagrum.Desktop\Services\WpfService.cs:line 65
   at Flagrum.Web.Features.AssetExplorer.Export.ExportWithDependenciesModal.Export() in C:\Code\Flagrum\Flagrum.Web\Features\AssetExplorer\Export\ExportWithDependenciesModal.razor:line 79
   at Flagrum.Web.Components.Controls.Button.HandleClick() in C:\Code\Flagrum\Flagrum.Web\Components\Controls\Button.razor:line 45
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
NotifyUnhandledException @ blazor.webview.js:1
```

## Workaround

While you should always prefer "Export with Dependencies" as it will grab any dependencies that exist if they are not in the same folder as the model, you can work around this issue by using "Export Folder" on the model folder and opting to export subdirectories as well.

![image](https://user-images.githubusercontent.com/25322543/195988854-28491d43-34a4-49fe-aba9-f9a192e49bae.png)

![image](https://user-images.githubusercontent.com/25322543/195988867-5a98d404-68cd-4ae2-9785-34604f32bc5b.png)

**Comment by Kizari** [comment]
This issue has been resolved as of Flagrum 1.3.1.
