### ISSUE TITLE
Database concurrency error rarely causes crash for some users

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#3]
When using the Mod Manager, the application can sometimes crash due to UI updates triggering multiple database reads on the same DbContext.

```
blazor.webview.js:1 
        
       Unable to set property 'Node' on object of type 'Flagrum.Web.Features.EarcMods.Modals.UriSelectModalRow'. The error was: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

This should be fixable by spinning up a new DbContext for the conflicting piece of UI code.

**Comment by Kizari** [comment]
This issue has been resolved as of Flagrum 1.2.5.
