### ISSUE TITLE
Quickly changing model previews results in a crash

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#33]
1) Go to a folder with multiple model gmdls
2) hold down
3) Receive the following error

```
       Cannot read properties of null (reading 'offsetLeft')
TypeError: Cannot read properties of null (reading 'offsetLeft')
    at Object.getElementLeftOffset (https://0.0.0.0/interop.js:84:43)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3332
    at new Promise (<anonymous>)
    at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3306)
    at https://0.0.0.0/_framework/blazor.webview.js:1:40526
    at EventTarget.<anonymous> (<anonymous>:7:80)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:37608)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Flagrum.Web.Features.AssetExplorer.Previews.ModelPreviewV2.OnAfterRenderAsync(Boolean firstRender) in C:\Code\Flagrum\Flagrum.Web\Features\AssetExplorer\Previews\ModelPreviewV2.razor:line 80
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Advice for others with this issue:
This can be easily prevented by letting models load before changing to the next model.

**Comment by Kizari** [comment]
This seems to only ever occur on subsequent model previews, so exception catching logic has been added to the resize code in the ModelPreview initialisation to simply ignore the problem and carry on as usual when this edge-case occurs. Because the viewer will have already been sized correctly on all other successful previews, there's no need to retry the call.

This is fixed in Flagrum 1.3.3.
