### ISSUE TITLE
Trying to use textures with invalid resolutions can crash the application

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#7]
If you are experiencing this issue, please see the **Workarounds** section at the bottom of this post for a solution.

A user reported the following issue.

When using a texture with an invalid resolution (i.e. not square numbers), the application crashed.

I am not sure whether this was related to a binmod project, or an EARC mod project. Regardless, both use the same texture conversion code, so the issue likely affects both.

The crash occurs due to a failure when generating mipmaps for the texture.

The workaround for this is to simply provide a texture with a valid resolution.

The proposed fix is as follows:

- This problem should be correctly detected during runtime, and an appropriate warning/error message displayed to the user to inform them of what went wrong. Ideally the exception type would be specific to prevent catching other issues under this same warning message.
- This warning message should link to appropriate documentation that explains what a valid resolution is and why it is required.
- The error message and supporting documentation should also be localised accordingly.

## Workarounds

Ensure your texture is 4x4 pixels or larger, and that the dimensions are a square number. Textures should never be larger than 4096x4096. Some examples of valid resolutions are:

- 4x4
- 32x32
- 512x512
- 1024x1024
- 1024x512
- 512x1024
- 2048x2048
- 4096x4096

**Comment by Rinual** [comment]
This issue can also be re-created via using textures under 16px or 4x4. 
```

System.AggregateException
Message: One or more errors occurred. (Value does not fall within the expected range.)
Stack Trace:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Flagrum.Web.Features.ModLibrary.Data.BuildContext.<>c__DisplayClass32_0.<<ProcessFmd>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Flagrum.Web.Features.ModLibrary.Data.BuildContext.<>c__DisplayClass32_0.<<ProcessFmd>b__0>d.MoveNext() in C:\Code\Flagrum\Flagrum.Web\Features\ModLibrary\Data\BuildContext.cs:line 152
--- End of stack trace from previous location ---
   at Flagrum.Web.Features.ModLibrary.Data.BuildContext.<>c__DisplayClass32_0.<<ProcessFmd>b__0>d.MoveNext() in C:\Code\Flagrum\Flagrum.Web\Features\ModLibrary\Data\BuildContext.cs:line 152
--- End of stack trace from previous location ---
   at Flagrum.Web.Features.ModLibrary.Data.BuildContext.ProcessFmd(Int32 index, String path) in C:\Code\Flagrum\Flagrum.Web\Features\ModLibrary\Data\BuildContext.cs:line 86
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Flagrum.Desktop.App.Main()
System.ArgumentException
Message: Value does not fall within the expected range.
Stack Trace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.ScratchImageImpl.GenerateMipMaps(TEX_FILTER_FLAGS filter, Int32 levels)
   at Flagrum.Web.Services.TextureConverter.BuildDds(TextureType type, ScratchImage image) in C:\Code\Flagrum\Flagrum.Web\Services\TextureConverter.cs:line 255
   at Flagrum.Web.Services.TextureConverter.ConvertWic(TextureType type, String name, Byte[] data) in C:\Code\Flagrum\Flagrum.Web\Services\TextureConverter.cs:line 203
   at Flagrum.Web.Services.TextureConverter.ToBtex(String name, String extension, TextureType type, Byte[] data) in C:\Code\Flagrum\Flagrum.Web\Services\TextureConverter.cs:line 120
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Flagrum.Web.Features.ModLibrary.Data.BuildContext.<>c__DisplayClass32_1.<ProcessFmd>b__1(Object data) in C:\Code\Flagrum\Flagrum.Web\Features\ModLibrary\Data\BuildContext.cs:line 141
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by Kizari** [comment]
It seems non-square resolutions also seem to work a lot of the time, so I'm not entirely sure what exactly sets this off. Perhaps certain numbers that just don't divide nicely? It would be best practice to use square resolutions anyway though.

**Comment by Kizari** [comment]
Since the exception doesn't seem to always occur with non-square resolutions, there's not really any way to reliably detect it to show any kind of message to the user. The BTEX code has also been largely rewritten at this point, so it's uncertain whether this issue still occurs or not. For now, closing this as it doesn't seem to be affecting anyone or anything.
